spring:
  application:
    name: ms-login
server:
  port: 8084
eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka-server:8761/eureka/
