spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-register
          uri: lb://MS-REGISTER
          predicates:
            - Path=/api/v1/register/**
        - id: ms-login
          uri: lb://MS-LOGIN
          predicates:
            - Path=/api/v1/login/**
eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8761/eureka/
